#!/usr/bin/env python3
"""Render the spec rulings registry to docs/spec/rulings.md.

CI regenerates this file and diffs it, so the site can never state a ruling the
package does not carry.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from limen.spec import all_decisions, spec_version  # noqa: E402

OUT = ROOT / "docs" / "spec" / "rulings.md"


def main() -> int:
    lines = [
        "# Spec rulings",
        "",
        "<!-- GENERATED by tools/render_rulings.py; do not edit by hand -->",
        "",
        f"Rulings spec version: **{spec_version()}**. A ruling is never edited to mean",
        "something else; it is superseded, and the spec version moves. `limen spec list`",
        "prints this same registry from the installed package.",
        "",
    ]
    group = None
    for decision in all_decisions():
        prefix = decision.id.rsplit("-", 1)[0]
        if prefix != group:
            group = prefix
            lines += [f"## {prefix}", ""]
        lines += [
            f"### {decision.id} — {decision.title}",
            "",
            f"*Status: {decision.status}.* {decision.text}",
            "",
        ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
