#!/usr/bin/env python3
"""The instrument's own sensitivity, measured: planted-truth sweep -> docs table.

For each (true gap, flaky fraction, k) grid point, R planted archives are
generated with derived seeds and pushed through the ordinary sign-stability and
MDD path; the table reports how often the gate (--require-sign-stable
--min-effect-vs-noise 1.0) passes. The published operating point per (k, phi)
is g80 — the smallest swept true gap passed at least 80% of the time — beside
the false-pass rate at true gap zero. Fully deterministic: fixed grid, derived
seeds, no wall clock.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from limen.canonical import derive_seed  # noqa: E402
from limen.noise import mdd_pair  # noqa: E402
from limen.ranking import draw_scores, pair_stability, single_draw_score_list  # noqa: E402
from limen.stats import sample_sd  # noqa: E402
from limen.synth import PlantedConfig, generate  # noqa: E402

OUT = ROOT / "docs" / "spec" / "sensitivity.md"

GAPS = (0.0, 0.005, 0.01, 0.02, 0.05)
PHIS = (0.02, 0.05, 0.15)
KS = (2, 4, 8)
N_ITEMS = 1500
TOP_MU = 0.6
SEED_LABEL = "sensitivity-v1"


def gate_passes(gap: float, phi: float, k: int, seed: int) -> bool:
    cfg = PlantedConfig(
        n_items=N_ITEMS,
        k=k,
        models=("a", "b"),
        mu=(TOP_MU, TOP_MU - gap),
        flaky_fraction=phi,
        with_timestamps=False,
        with_raw_hashes=False,
        with_versions=False,
    )
    archive, _ = generate(cfg, seed=seed)
    ds = draw_scores(archive, "synthetic")
    block = pair_stability(ds, "a", "b")
    if block["sign_stability"]["ruling"] != "SIGN-STABLE":
        return False
    sd_a = sample_sd(single_draw_score_list(ds, "a"))
    sd_b = sample_sd(single_draw_score_list(ds, "b"))
    mdd = mdd_pair(sd_a, sd_b, k, len(ds.items))
    delta = abs(block["pooled"]["delta_pool"])
    if mdd["value"] == 0.0:
        return delta > 0.0  # degenerate zero spread: pass-with-warning path
    return delta / mdd["value"] >= 1.0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--replicates", type=int, default=200)
    args = parser.parse_args()
    replicates = args.replicates

    rows: list[tuple[float, float, int, float]] = []
    for k in KS:
        for phi in PHIS:
            for gap in GAPS:
                passes = sum(
                    1
                    for r in range(replicates)
                    if gate_passes(
                        gap, phi, k, derive_seed(SEED_LABEL, gap, phi, k, r)
                    )
                )
                rows.append((gap, phi, k, passes / replicates))
                print(f"k={k} phi={phi} gap={gap}: pass rate {passes / replicates:.3f}", flush=True)

    lines = [
        "# Gate sensitivity",
        "",
        "<!-- GENERATED by tools/render_sensitivity.py; do not edit by hand -->",
        "",
        f"Planted-truth sweep, {replicates} replicate seeds per point, n = {N_ITEMS}",
        "items, two models, per-draw flaky success probability q = 0.5, gate policy",
        "`--require-sign-stable --min-effect-vs-noise 1.0`. Seeds are derived from the",
        f"label `{SEED_LABEL}`; the table regenerates byte-identically.",
        "",
        "A pass rate at true gap 0 is a **false pass**: the gate approving a claim",
        "where no true difference exists. `g80` is the smallest swept true gap the",
        "gate passes at least 80% of the time — the gate's detectable-gap resolution",
        "at that noise level.",
        "",
        "| k | flaky fraction | " + " | ".join(f"gap {g}" for g in GAPS) + " | g80 |",
        "|---|---|" + "---|" * (len(GAPS) + 1),
    ]
    for k in KS:
        for phi in PHIS:
            cells = []
            g80 = None
            for gap in GAPS:
                rate = next(r for g, p, kk, r in rows if (g, p, kk) == (gap, phi, k))
                cells.append(f"{rate:.3f}")
                if g80 is None and gap > 0 and rate >= 0.80:
                    g80 = gap
            lines.append(
                f"| {k} | {phi} | " + " | ".join(cells) + f" | {g80 if g80 is not None else '> ' + str(GAPS[-1])} |"
            )
    lines += [
        "",
        "The gap-0 column is the measured false-pass rate. Rulings scope applies: a",
        "gate pass is a statement about this synthetic noise model at these",
        "parameters, not a certificate for any real benchmark (NO_K1_CERTIFICATE).",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
